periods:
  aff_searches:
    three_periods:
      hourly: 'http://tp.aviasales.ru/report.php?r=89&u1=%s&m=1&h=c77d52ca5f5087735652bcd45ce0490e146e1fc6&export=json'
      fifteen_min: 'http://tp.aviasales.ru/report.php?r=96&u1=%s&m=1&h=74adefa7ee34bc1ca73a9c2fdfa6d09f33dcc1cd&export=json'
    one_periods:
      daily: 'http://tp.aviasales.ru/report.php?r=104&u1=%s&u2=searches&m=1&h=e23eb4e8e3946bd299deee890996c5c3ebec77fa&export=json'
      monthly: 'http://tp.aviasales.ru/report.php?r=154&u1=%s&u2=searches&m=1&h=67a94a42fd90edc5003672ea3712fce050ee7bc7&export=json'
  aff_clicks:
    three_periods:
      hourly: 'http://tp.aviasales.ru/report.php?r=90&u1=%s&m=1&h=f6cd4db67bf01d95951e9a42279a23e12eb35b9d&export=json'
      fifteen_min: 'http://tp.aviasales.ru/report.php?r=99&u1=%s&m=1&h=67a94a42fd90edc5003672ea3712fce050ee7bc7&export=json'
    one_periods:
      daily: 'http://tp.aviasales.ru/report.php?r=104&u1=%s&u2=clicks&m=1&h=e23eb4e8e3946bd299deee890996c5c3ebec77fa&export=json'
      monthly: 'http://tp.aviasales.ru/report.php?r=154&u1=%s&u2=clicks&m=1&h=67a94a42fd90edc5003672ea3712fce050ee7bc7&export=json'
  aff_bookings:
     one_periods:
      daily: 'http://tp.aviasales.ru/report.php?r=104&u1=%s&u2=bookings&m=1&h=e23eb4e8e3946bd299deee890996c5c3ebec77fa&export=json'
      monthly: 'http://tp.aviasales.ru/report.php?r=154&u1=%s&u2=bookings&m=1&h=67a94a42fd90edc5003672ea3712fce050ee7bc7&export=json'
  aff_paidbookings:
    three_periods:
      hourly: 'http://tp.aviasales.ru/report.php?r=91&u1=%s&m=1&h=d0ba89de5088c9d7b3d8044f56eb16369de435e4&export=json'
      fifteen_min: 'http://tp.aviasales.ru/report.php?r=98&u1=%s&m=1&h=67a94a42fd90edc5003672ea3712fce050ee7bc7&export=json'
    one_periods:
      daily: 'http://tp.aviasales.ru/report.php?r=104&u1=%s&u2=paid_bookings&m=1&h=e23eb4e8e3946bd299deee890996c5c3ebec77fa&export=json'
      monthly: 'http://tp.aviasales.ru/report.php?r=154&u1=%s&u2=paid_bookings&m=1&h=67a94a42fd90edc5003672ea3712fce050ee7bc7&export=json'
  aff_amount:
    three_periods:
      hourly: 'http://tp.aviasales.ru/report.php?r=92&u1=%s&m=1&h=e06675a675f2284f17f7deb52112b38b9dad2fd1&export=json'
    one_periods:
      hourly: ''
      daily: 'http://tp.aviasales.ru/report.php?r=103&u1=%s&m=1&h=13b886260108e63c0204426e2c7740ea3afcaa90&export=json'
      monthly: 'http://tp.aviasales.ru/report.php?r=153&u1=%s&m=1&h=0d085a06452a6a9b8287129f06cfa38f700a2d6d&export=json'
  aff_profit:
    three_periods:
      hourly: ''
      daily: ''
    one_periods:
      hourly: ''
      daily: 'http://tp.aviasales.ru/report.php?r=102&u1=%s&m=1&h=32e0365ff539838c9be01409d4536a968306e192&export=json'
      monthly: 'http://tp.aviasales.ru/report.php?r=155&u1=%s&m=1&h=716798adea17cd22d8717e033e2c644c5dd5bf23&export=json'
  widget_statistics_inits:
    three_periods:
      hourly: 'http://tp.aviasales.ru/report.php?r=95&u1=%s&u2=inits&m=1&h=5781b1205010ca590bfc607aa5dcc0f480b41b7e&export=json'
  widget_statistics_shows:
    three_periods:
      hourly: 'http://tp.aviasales.ru/report.php?r=95&u1=%s&u2=shows&m=1&h=5781b1205010ca590bfc607aa5dcc0f480b41b7e&export=json'
  widget_statistics_leads:
    three_periods:
      hourly: 'http://tp.aviasales.ru/report.php?r=95&u1=%s&u2=leads&m=1&h=5781b1205010ca590bfc607aa5dcc0f480b41b7e&export=json'
  widget_statistics_searches:
    three_periods:
      hourly: 'http://tp.aviasales.ru/report.php?r=95&u1=%s&u2=searches&m=1&h=5781b1205010ca590bfc607aa5dcc0f480b41b7e&export=json'
  widget_statistics_clicks:
    three_periods:
      hourly: 'http://tp.aviasales.ru/report.php?r=95&u1=%s&u2=clicks&m=1&h=5781b1205010ca590bfc607aa5dcc0f480b41b7e&export=json'
  widget_statistics_bookings:
    three_periods:
      hourly: 'http://tp.aviasales.ru/report.php?r=95&u1=%s&u2=bookings&m=1&h=5781b1205010ca590bfc607aa5dcc0f480b41b7e&export=json'
  widget_statistics_profit:
    three_periods:
      hourly: 'http://tp.aviasales.ru/report.php?r=95&u1=%s&u2=profit&m=1&h=5781b1205010ca590bfc607aa5dcc0f480b41b7e&export=json'
  widget_paid_bookings_profit:
    three_periods:
      hourly: 'http://tp.aviasales.ru/report.php?r=95&u1=%s&u2=paid_bookings_profit&m=1&h=5781b1205010ca590bfc607aa5dcc0f480b41b7e&export=json'
  combined_wl_searches:
    one_periods:
      daily: 'http://tp.aviasales.ru/report.php?r=130&u1=%s&u2=searches&m=1&h=69af489f3a4bec6beafda37a5d7e999e51548cb3&export=json'
  combined_wl_bookings:
    one_periods:
      daily: 'http://tp.aviasales.ru/report.php?r=130&u1=%s&u2=bookings&m=1&h=69af489f3a4bec6beafda37a5d7e999e51548cb3&export=json'
  combined_wl_clicks:
    one_periods:
      daily: 'http://tp.aviasales.ru/report.php?r=130&u1=%s&u2=clicks&m=1&h=69af489f3a4bec6beafda37a5d7e999e51548cb3&export=json'
  combined_wl_paid_bookings_profit:
    one_periods:
      daily: 'http://tp.aviasales.ru/report.php?r=130&u1=%s&u2=paid_bookings_profit&m=1&h=69af489f3a4bec6beafda37a5d7e999e51548cb3&export=json'
  combined_wl_registration:
    one_periods:
      daily: 'http://tp.aviasales.ru/report.php?r=133&u1=%s&m=1&h=c055e081f5e89a38b0597debec1c00c26e280a8c&export=json'
  combined_wl_active_wl:
    one_periods:
      daily: 'http://tp.aviasales.ru/report.php?r=134&u1=%s&m=1&h=9506a1e53a068b284e638f40257125b310b6bc9e&export=json'
  whitelabels_searches:
    one_periods:
      daily: 'http://tp.aviasales.ru/report.php?r=131&u1=%s&u2=searches&m=1&h=87e698d690eba65d61a89c7f28083c6208dbad66&export=json'
  whitelabels_bookings:
    one_periods:
      daily: 'http://tp.aviasales.ru/report.php?r=131&u1=%s&u2=bookings&m=1&h=87e698d690eba65d61a89c7f28083c6208dbad66&export=json'
  whitelabels_clicks:
    one_periods:
      daily: 'http://tp.aviasales.ru/report.php?r=131&u1=%s&u2=clicks&m=1&h=87e698d690eba65d61a89c7f28083c6208dbad66&export=json'
  whitelabels_paid_bookings_profit:
    one_periods:
      daily: 'http://tp.aviasales.ru/report.php?r=131&u1=%s&u2=paid_bookings_profit&m=1&h=87e698d690eba65d61a89c7f28083c6208dbad66&export=json'
  whitelabels_registration:
    one_periods:
      daily: 'http://tp.aviasales.ru/report.php?r=132&u1=%s&m=1&h=f203f61e14d72d4a5013f931adb808b67c85b550&export=json'
custom:
  widget_events:
    url: 'http://tp.aviasales.ru/report.php?r=73&u1=%s&m=1&h=8cd6b09cb12eb6ce7e29859c9b13efe1cf8d81bf&export=json'
    detailed_url: 'http://tp.aviasales.ru/report.php?r=85&u1=%s&m=1&h=c9f043f6692c1c10598c3463043c5ba3823adec9&export=json'
  widget_statistics:
    url: 'http://tp.aviasales.ru/report.php?r=74&u1=%s&m=1&h=661221091ae4f65a425e47e75d7895beeefe66b5&export=json'
    detailed_url: 'http://tp.aviasales.ru/report.php?r=84&u1=%s&m=1&h=9c1b9554eb3e62a43ac5c4245c01bc3e19140469&export=json'
